#!/usr/bin/env python3
"""Regenerate tools/banned-hashes.txt from the plaintext term list.

The plaintext list lives OUTSIDE this public repo, at
~/.config/hwk-site/banned-terms.txt. A public repo containing a readable list of
our customers' names would defeat the whole point of the gate, so only salted
hashes are committed.

Honest about the limit: company names are low-entropy and the salt is committed
alongside the hashes so CI can verify. A determined reader with a company-name
dictionary could confirm a guess. This is obfuscation, not encryption. It stops
casual reading and accidental disclosure, which is the actual threat here -- it
is not a secrecy guarantee. The real protection is that these names never get
written into the repo in the first place.

Run after editing the term list:
    python3 tools/make-hashes.py
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "tools" / "banned-hashes.txt"
TERMS = Path.home() / ".config" / "hwk-site" / "banned-terms.txt"

# Committed so CI can reproduce the hashes. See the docstring on why that is fine.
SALT = "hwk-site-scrub-v1"


def normalize(text: str) -> str:
    return " ".join(re.sub(r"[^a-z0-9]+", " ", text.lower()).split())


def collision_report(terms: list[str]) -> list[tuple[str, str, int, str]]:
    """Find terms that already match legitimate published content.

    This check exists because a colliding term becomes an opaque hash that
    blocks a commit with no way to tell which word is at fault. The live
    example: "Brazil" is both an internal build system and a real line in
    Heewon's own biography ("Seoul, Brazil, Sydney"). A term that collides
    must be handled by a context-anchored regex in scrub.py, not a bare hash.
    """
    hits = []
    for path in REPO.rglob("*"):
        if not path.is_file() or ".git/" in str(path.relative_to(REPO)):
            continue
        if path.suffix.lower() not in {".html", ".css", ".js", ".md", ".txt", ".svg"}:
            continue
        rel = str(path.relative_to(REPO))
        if rel.startswith("tools/"):
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (UnicodeDecodeError, OSError):
            continue
        for term in terms:
            pattern = re.compile(r"\b" + re.escape(term) + r"\b", re.I)
            for lineno, line in enumerate(lines, 1):
                if pattern.search(line):
                    hits.append((term, rel, lineno, line.strip()[:70]))
                    break
    return hits


def main() -> int:
    if not TERMS.exists():
        print(f"error: no term list at {TERMS}", file=sys.stderr)
        print("Create it, one term per line, '#' for comments.", file=sys.stderr)
        return 1

    terms = []
    for raw in TERMS.read_text().splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            norm = normalize(line)
            if norm:
                terms.append(norm)

    if not terms:
        print(f"error: {TERMS} has no usable terms", file=sys.stderr)
        return 1

    # Refuse to bake in a term that collides with content already published.
    collisions = collision_report(terms)
    if collisions:
        print("error: these terms match legitimate content already in the site tree.\n"
              "       Hashing them would block commits with an undebuggable error.\n"
              "       Remove them from the term list and handle them with a\n"
              "       context-anchored regex in tools/scrub.py instead.\n", file=sys.stderr)
        for term, rel, lineno, excerpt in collisions:
            print(f"  {term!r}  ->  {rel}:{lineno}\n      > {excerpt}", file=sys.stderr)
        return 1

    max_n = max(len(t.split()) for t in terms)
    digests = sorted({
        hashlib.sha256((SALT + "\x1f" + t).encode()).hexdigest()[:32] for t in terms
    })

    OUT.write_text(
        "# Salted hashes of confidential terms the scrub gate must block.\n"
        "# Generated by tools/make-hashes.py -- do not edit by hand.\n"
        "# The plaintext list is deliberately not in this repo.\n"
        f"# salt: {SALT}\n"
        f"# max-ngram: {max_n}\n"
        f"# count: {len(digests)}\n"
        + "\n".join(digests) + "\n"
    )
    print(f"wrote {OUT.relative_to(REPO)}: {len(digests)} hashes, max n-gram {max_n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
